### ISSUE TITLE
How to use mp3 to build database?

### ISSUE THREAD

**Issue by Erickrus** [mikezzb/song-recognition#1]
I managed to run query_by_singing.ipynb on colab. 
It seems the whole process starts with midi files. 

If I want to create the music database based on mp3, can you give me some hints on: 
1. How to use mp3 as the database input? 
2. Or do I need to use a third party mp3 to midi file to do this?

**Comment by mikezzb** [comment]
Hi, you can use a third-party mp3 to midi file to do this.

If your music is polyphonic, you may consider performing source separation using models like demucs to extract the main melody first before converting it to MIDI.

**Comment by Erickrus** [comment]
Many thanks, I actually find the tool

1. split voice and music
2. use a tool to create midi from wave for both voice and music

[时间都去哪了.zip](https://github.com/mikezzb/song-recognition/files/11542213/default.zip)

But the chord is low volume and I'm not sure if the music tempo will affect the search ?
